<?php

namespace Database\Seeders;

use App\Models\Classification;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ClassificationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ['code' => '000', 'parent_code' => null, 'name' => 'UMUM'],
            ['code' => '000.1', 'parent_code' => '000', 'name' => 'KETATAUSAHAAN DAN KERUMAHTANGGAAN'],
            ['code' => '000.1.2', 'parent_code' => '000.1', 'name' => 'Perjalanan Dinas Dalam Negeri'],
            ['code' => '000.1.2.1', 'parent_code' => '000.1.2', 'name' => 'Perjalanan Dinas Kepala Daerah'],
            ['code' => '000.1.2.2', 'parent_code' => '000.1.2', 'name' => 'Perjalanan Dinas DPRD'],
            ['code' => '000.1.2.3', 'parent_code' => '000.1.2', 'name' => 'Perjalanan Dinas Pegawai'],
            ['code' => '000.1.4', 'parent_code' => '000.1', 'name' => 'Penggunaan Fasilitas Kantor (antara lain: \nPermintaan dan penggunaan ruang, gedung, \nkendaraan, wisma, rumah dinas dan fasilitas \nkantor lainnya)'],
            ['code' => '000.1.5', 'parent_code' => '000.1', 'name' => 'Rapat pimpinan antara lain: Notula/Risalah Rapat'],
            ['code' => '000.1.8', 'parent_code' => '000.1', 'name' => 'Pemeliharaan Gedung, Taman dan Peralatan Kantor'],
            ['code' => '000.1.8.1', 'parent_code' => '000.1.8', 'name' => 'Pertamanan/Landscape'],
            ['code' => '000.1.8.2', 'parent_code' => '000.1.8', 'name' => 'Penghijauan'],
            ['code' => '000.1.8.3', 'parent_code' => '000.1.8', 'name' => 'Perbaikan Gedung'],
            ['code' => '000.1.8.4', 'parent_code' => '000.1.8', 'name' => 'Perbaikan Peralatan Kantor'],
            ['code' => '000.1.8.5', 'parent_code' => '000.1.8', 'name' => 'Perbaikan Rumah Dinas/Wisma'],
            ['code' => '000.1.8.6', 'parent_code' => '000.1.8', 'name' => 'Kebersihan Gedung dan Taman'],
            ['code' => '000.1.9', 'parent_code' => '000.1', 'name' => 'Pengelolaan Jaringan Listrik, Air, Telepon dan \nKomputer'],
            ['code' => '000.1.9.1', 'parent_code' => '000.1.9', 'name' => 'Perbaikan/Pemeliharaan'],
            ['code' => '000.1.9.2', 'parent_code' => '000.1.9', 'name' => 'Pemasangan'],
            ['code' => '000.1.10', 'parent_code' => '000.1', 'name' => 'Ketertiban dan Keamanan'],
            ['code' => '000.1.10.1', 'parent_code' => '000.1.10', 'name' => 'Pengamanan, \nPengawalan \nPenjagaan, \nterhadap \ndan \nPejabat, \nKantor dan Rumah Dinas'],
            ['code' => '000.1.10.2', 'parent_code' => '000.1.10', 'name' => 'Laporan Ketertiban dan Keamanan'],
            ['code' => '000.1.11', 'parent_code' => '000.1', 'name' => 'Administrasi Pengelolaan Parkir'],
            ['code' => '000.1.12', 'parent_code' => '000.1', 'name' => 'Administrasi Pakaian Dinas Pegawai, Satpam, Petugas Kebersihan dan Pegawai lainnya'],
            ['code' => '000.2', 'parent_code' => '000', 'name' => 'PERLENGKAPAN'],
            ['code' => '000.2.1', 'parent_code' => '000.2', 'name' => 'Inventarisasi dan Penyimpanan'],
            ['code' => '000.2.1.1', 'parent_code' => '000.2.1', 'name' => 'Data hasil inventarisasi dan penyimpanan'],
            ['code' => '000.2.1.2', 'parent_code' => '000.2.1', 'name' => 'Laporan dan evaluasi inventarisasi \ndan penyimpanan'],
            ['code' => '000.2.2', 'parent_code' => '000.2', 'name' => 'Pemeliharaan peralatan kantor'],
            ['code' => '000.2.2.1', 'parent_code' => '000.2.2', 'name' => 'Data hasil pemeliharaan kantor'],
            ['code' => '000.2.2.2', 'parent_code' => '000.2.2', 'name' => 'Laporan dan evaluasi  \nPemeliharaan kantor'],
            ['code' => '000.2.3', 'parent_code' => '000.2', 'name' => 'Distribusi'],
            ['code' => '000.2.3.1', 'parent_code' => '000.2.3', 'name' => 'Barang habis pakai'],
            ['code' => '000.2.3.2', 'parent_code' => '000.2.3', 'name' => 'Barang milik daerah'],
            ['code' => '000.2.4', 'parent_code' => '000.2', 'name' => 'Penghapusan Barang Milik Daerah antara lain: \nKeputusan Pembentukan Tim, Berita Acara  \nPenghapusan Barang Milik Daerah, Daftar Barang  \nyang dihapuskan, Laporan Hasil Pelaksanaan \nPenghapusan BMD termasuk didalamnya proses \nlelang penghapusan'],
            ['code' => '000.2.5', 'parent_code' => '000.2', 'name' => 'Pengelolaan Database Barang Milik Daerah'],
            ['code' => '000.3', 'parent_code' => '000', 'name' => 'PENGADAAN'],
            ['code' => '000.4', 'parent_code' => '000', 'name' => 'PERPUSTAKAAN'],
            ['code' => '000.5', 'parent_code' => '000', 'name' => 'KEARSIPAN'],
            ['code' => '000.5.3', 'parent_code' => '000.5', 'name' => 'Pengelolaan Arsip Dinamis'],
            ['code' => '000.5.3.1', 'parent_code' => '000.5.3', 'name' => 'Penciptaan (antara lain: Buku Registrasi Naskah Masuk dan Keluar, Buku Agenda, Kartu Kendali, Lembar Pengantar/Buku Ekspedisi)'],
            ['code' => '000.5.3.2', 'parent_code' => '000.5.3', 'name' => 'Pemberkasan Arsip Aktif (antara lain: daftar berkas dan daftar isi berkas)'],
            ['code' => '000.5.3.3', 'parent_code' => '000.5.3', 'name' => 'Penataan Arsip Inaktif (antara lain: daftar arsip arsip inaktif tematik)'],
            ['code' => '000.5.3.4', 'parent_code' => '000.5.3', 'name' => 'Penggunaan (antara lain: daftar arsip dinamis berdasarkan sistem klasifikasi keamanan dan akses arsip dinamis, bukti peminjaman arsip)'],
            ['code' => '000.5.3.5', 'parent_code' => '000.5.3', 'name' => 'Autentikasi Arsip Dinamis (antara lain: pembuktian autentisitas, pendapat tenaga ahli, pengujian, penetapan autentisitas dinamis)'],
            ['code' => '000.5.6', 'parent_code' => '000.5', 'name' => 'Penyusutan Arsip'],
            ['code' => '000.5.6.1', 'parent_code' => '000.5.6', 'name' => 'Pemindahan Arsip (antara lain: Berita Acara Pemindahan, Daftar Arsip yang dipindahkan)'],
            ['code' => '000.5.6.2', 'parent_code' => '000.5.6', 'name' => 'Pemusnahan Arsip (antara lain: SK Penetapan Panitia Penilai Arsip, Pertimbangan Panitia Permintaan Persetujuan Penilai, Kepala ANRI Untuk pemusnahan arsip dengan Retensi sekurang-kurangnya 10 \n(sepuluh) \ntahun \natau    \nPersetujuan Kepala Daerah selaku   \nPimpinan  \nPencipta Arsip untuk \npemusnahan   \nretensi di bawah   \ntahun,    \narsip   \n10    \ndengan  \n(sepuluh) \nPenetapan Arsip Yang     \nDimusnahkan,     \nBerita     \nAcara \nPemusnahan   Arsip,  Daftar Arsip \nYang Dimusnahkan.'],
            ['code' => '000.5.6.3', 'parent_code' => '000.5.6', 'name' => 'Penyerahan   Arsip   Statis   (antara \nlain: Pembentukan  panitia  penilai,  \nNotulen \nrapat \npanitia, \nSurat   \nPertimbangan panitia penilai,   Surat  \npersetujuan dari Kepala Lembaga    \nKearsipan, \nSurat \nPernyataan  \nautentik, terpercaya, utuh, dan   \ndigunakan   dari   pencipta    arsip, \nKeputusan Penetapan  Penyerahan, \nBerita Acara  Penyerahan  Arsip,  \nDaftar Arsip yang diserahkan)'],
            ['code' => '000.8', 'parent_code' => '000', 'name' => 'ORGANISASI DAN TATA LAKSANA'],
            ['code' => '000.8.1', 'parent_code' => '000.8', 'name' => 'Struktur    Organisasi    di    lingkungan     \n Pemerintahan Daerah Kab/Kota'],
            ['code' => '000.8.2', 'parent_code' => '000.8', 'name' => 'Uraian Jabatan'],
            ['code' => '000.8.2.1', 'parent_code' => '000.8.2', 'name' => 'Analisa Jabatan'],
            ['code' => '000.8.2.2', 'parent_code' => '000.8.2', 'name' => 'Analisa Beban Kerja'],
            ['code' => '000.8.3', 'parent_code' => '000.8', 'name' => 'Ketatalaksanaan'],
            ['code' => '000.8.3.1', 'parent_code' => '000.8.3', 'name' => 'Proses Bisnis'],
            ['code' => '000.8.3.2', 'parent_code' => '000.8.3', 'name' => 'Standar Pelayanan'],
            ['code' => '000.8.3.3', 'parent_code' => '000.8.3', 'name' => 'Standar Operasional Prosedur'],
            ['code' => '000.8.3.4', 'parent_code' => '000.8.3', 'name' => 'Pelayanan Publik'],
            ['code' => '400.3', 'parent_code' => null, 'name' => 'PENDIDIKAN'],
            ['code' => '400.3.1', 'parent_code' => '400.3', 'name' => 'Kebijakan di bidang Pendidikan yang dilakukan oleh Pemerintah Daerah'],
            ['code' => '400.3.4', 'parent_code' => '400.3', 'name' => 'Kursus/Pelatihan Pendidik dan Tenaga Pendidik'],
            ['code' => '400.3.7', 'parent_code' => '400.3', 'name' => 'Pembinaan Pendidik dan Tenaga Pendidik'],
            ['code' => '400.3.7.4', 'parent_code' => '400.3.7', 'name' => 'Penghargaan     guru      dan tenaga kependidikan'],
            ['code' => '400.3.7.5', 'parent_code' => '400.3.7', 'name' => 'Peningkatan kesejahteraan guru'],
            ['code' => '400.3.7.6', 'parent_code' => '400.3.7', 'name' => 'Sosialisasi, bimtek'],
            ['code' => '400.3.7.7', 'parent_code' => '400.3.7', 'name' => 'Block Grant'],
            ['code' => '400.3.8', 'parent_code' => '400.3', 'name' => 'Sekolah Menengah Atas'],
            ['code' => '400.3.8.1', 'parent_code' => '400.3.8', 'name' => 'Kurikulum'],
            ['code' => '400.3.8.2', 'parent_code' => '400.3.8', 'name' => 'Bahan Ajar'],
            ['code' => '400.3.8.3', 'parent_code' => '400.3.8', 'name' => 'Pelatihan'],
            ['code' => '400.3.8.5', 'parent_code' => '400.3.8', 'name' => 'Bimbingan teknis/sosialisasi'],
            ['code' => '400.3.8.6', 'parent_code' => '400.3.8', 'name' => 'Lomba, Sayembara, festival'],
            ['code' => '400.3.8.7', 'parent_code' => '400.3.8', 'name' => 'Bantuan operasional Sekolah (BOS)'],
            ['code' => '400.3.8.8', 'parent_code' => '400.3.8', 'name' => 'Bantuan siswa miskin'],
            ['code' => '400.3.10', 'parent_code' => '400.3', 'name' => 'Pendidik dan Tenaga Pendidik'],
            ['code' => '400.3.10.1', 'parent_code' => '400.3.10', 'name' => 'Pendataan dan Pemetaan'],
            ['code' => '400.3.10.2', 'parent_code' => '400.3.10', 'name' => 'Uji Kompetensi Guru'],
            ['code' => '400.3.10.3', 'parent_code' => '400.3.10', 'name' => 'Sertifikasi Guru'],
            ['code' => '400.3.10.4', 'parent_code' => '400.3.10', 'name' => 'Penilaian  prestasi    kerja    guru    dan pengawas sekolah'],
            ['code' => '400.3.10.5', 'parent_code' => '400.3.10', 'name' => 'Penghargaan      guru      dan     tenaga kependidikan'],
            ['code' => '400.3.10.6', 'parent_code' => '400.3.10', 'name' => 'Peningkatan  kesejahteraan  guru  dan tenaga pendidik'],
            ['code' => '400.3.11', 'parent_code' => '400.3', 'name' => 'Penilaian Pendidikan'],
            ['code' => '400.3.11', 'parent_code' => '400.3', 'name' => 'Penilaian Akademik'],
            ['code' => '400.3.12', 'parent_code' => '400.3', 'name' => 'Penilaian Non Akademik'],
            ['code' => '400.3.13', 'parent_code' => '400.3', 'name' => 'Analisis dan Sistem Informasi Penilaian'],
            ['code' => '400.3.12', 'parent_code' => '400.3', 'name' => 'Data dan Statistik Pendidikan'],
            ['code' => '400.3.12.1', 'parent_code' => '400.3.12', 'name' => 'Data    peserta    didik,    pendidik   dan tenaga kependidikan'],
            ['code' => '400.3.12.2', 'parent_code' => '400.3.12', 'name' => 'Data   Satuan  Pendidikan  dan Proses Pembelajaran'],
            ['code' => '400.3.13', 'parent_code' => '400.3', 'name' => 'Prasarana dan Sarana Pendidikan'],
            ['code' => '400.3.13.1', 'parent_code' => '400.3.13', 'name' => 'Prasarana Pendidikan'],
            ['code' => '400.3.13.2', 'parent_code' => '400.3.13', 'name' => 'Sarana Pendidikan'],
            ['code' => '400.3.13.3', 'parent_code' => '400.3.13', 'name' => 'Monitoring dan Evaluasi'],
            ['code' => '400.14', 'parent_code' => null, 'name' => 'HUBUNGAN MASYARAKAT'],
            ['code' => '400.14.5', 'parent_code' => '400.14', 'name' => 'Hubungan antar lembaga dan Pemerintahan Daerah'],
            ['code' => '400.14.5.1', 'parent_code' => '400.14.5', 'name' => 'Hubungan \npemerintah \nantar \nlembaga'],
            ['code' => '400.14.5.2', 'parent_code' => '400.14.5', 'name' => 'Hubungan dengan organisasi sosial / LSM'],
            ['code' => '400.14.5.3', 'parent_code' => '400.14.5', 'name' => 'Hubungan dengan perusahaan'],
            ['code' => '400.14.5.4', 'parent_code' => '400.14.5', 'name' => 'Hubungan dengan Perguruan Tinggi/ sekolah, termasuk magang, Pendidikan Sistem Ganda (PSG)/ Praktik Kerja Lapang (PKL)'],
            ['code' => '400.14.5.5', 'parent_code' => '400.14.5', 'name' => 'Forum Kehumasan'],
            ['code' => '400.14.5.6', 'parent_code' => '400.14.5', 'name' => 'Hubungan dengan Media Massa'],
            ['code' => '400.14.8', 'parent_code' => '400.14', 'name' => 'Penerbitan Majalah, buletin, koran dan jurnal'],
            ['code' => '400.14.9', 'parent_code' => '400.14', 'name' => 'Publikasi melalui media cetak maupun  elektronik'],
            ['code' => '400.14.10', 'parent_code' => '400.14', 'name' => 'Pameran/ sayembara/ lomba/ festival, pembuatan spanduk dan iklan'],
            ['code' => '400.14.11', 'parent_code' => '400.14', 'name' => 'Penghargaan/tanda kenang-kenangan'],
            ['code' => '400.14.12', 'parent_code' => '400.14', 'name' => 'Ucapan Terima kasih, Ucapan Selamat, Bela Sungkawa, Permohonan Maaf'],
            ['code' => '800', 'parent_code' => null, 'name' => 'KEPEGAWAIAN'],
            ['code' => '800.1.4', 'parent_code' => '800', 'name' => 'Pengembangan Karir'],
            ['code' => '800.1.4.1', 'parent_code' => '800.1.4', 'name' => 'Usulan Tugas Belajar/ Izin Belajar/ \nDiklat/ Kursus/ Magang/ Ujian  \nDinas/ Praktik Kerja di Instansi \nlain/ Pertukaran antar ASN dengan \npegawai swasta'],
            ['code' => '800.1.4.2', 'parent_code' => '800.1.4', 'name' => 'Penyesuaian ijazah'],
            ['code' => '800.1.4.3', 'parent_code' => '800.1.4', 'name' => 'Penyusunan Sistem Karier'],
            ['code' => '800.1.4.4', 'parent_code' => '800.1.4', 'name' => 'Standar Kinerja Pegawai (SKP) dan Penilaian Prestasi Kerja'],
            ['code' => '800.1.4.5', 'parent_code' => '800.1.4', 'name' => 'Angka Kredit antara lain: Pengajuan Daftar Usul Kredit, Pengajuan Angka Penilaian Daftar Pengajuan Angka Kredit'],
            ['code' => '800.1.11', 'parent_code' => '800', 'name' => 'Administrasi Pegawai'],
            ['code' => '800.1.11.1', 'parent_code' => '800.1.11', 'name' => 'Surat Perintah Dinas/Surat Tugas'],
            ['code' => '800.1.11.2', 'parent_code' => '800.1.11', 'name' => 'Cuti Sakit'],
            ['code' => '800.1.11.3', 'parent_code' => '800.1.11', 'name' => 'Cuti Bersalin'],
            ['code' => '800.1.11.4', 'parent_code' => '800.1.11', 'name' => 'Cuti Tahunan'],
            ['code' => '800.1.11.5', 'parent_code' => '800.1.11', 'name' => 'Cuti Alasan Penting'],
            ['code' => '800.1.11.6', 'parent_code' => '800.1.11', 'name' => 'Cuti Besar'],
            ['code' => '800.1.11.7', 'parent_code' => '800.1.11', 'name' => 'Cuti Di luar Tanggungan Negara'],
            ['code' => '800.1.11.8', 'parent_code' => '800.1.11', 'name' => 'Karpeg/KPE/Karis/Karsu'],
            ['code' => '800.1.11.9', 'parent_code' => '800.1.11', 'name' => 'Keanggotaan Organisasi Profesi/ Kedinasan'],
            ['code' => '800.1.11.10', 'parent_code' => '800.1.11', 'name' => 'Laporan Pajak Penghasilan Pribadi (LP2P)'],
            ['code' => '800.1.11.11', 'parent_code' => '800.1.11', 'name' => 'Keterangan Penerimaan Pembayaran 2)'],
            ['code' => '800.1.11.12', 'parent_code' => '800.1.11', 'name' => 'Daftar Urut Kepangkatan (DUK)'],
            ['code' => '800.1.11.13', 'parent_code' => '800.1.11', 'name' => 'Pengurusan   Kenaikan   Gaji Berkala, Mutasi Gaji/tunjangan'],
            ['code' => '900', 'parent_code' => null, 'name' => 'KEUANGAN'],
            ['code' => '900.1', 'parent_code' => '900', 'name' => 'KEUANGAN DAERAH'],
            ['code' => '900.1.1', 'parent_code' => '900.1', 'name' => 'Rencana Anggaran Pendapatan dan Belanja \nDaerah (RAPBD) dan Anggaran Pendapatan dan \nBelanja Daerah Perubahan (APBD-P)'],
            ['code' => '900.1.2', 'parent_code' => '900.1', 'name' => 'Penyusunan Anggaran'],
            ['code' => '900.1.3', 'parent_code' => '900.1', 'name' => 'Pelaksanaan Anggaran'],
        ];

        usort($data, function ($a, $b) {
            return substr_count($a['code'], '.') <=> substr_count($b['code'], '.');
        });
        
        foreach ($data as $item) {
            Classification::updateOrCreate(
                ['code' => $item['code']],
                $item
            );
        }
    }
}
